### ISSUE TITLE
api url

### ISSUE THREAD

**Issue by GeorgeFischhof** [bakog/pyweather#2]
most nem kell, de celszeru szetszedni legalabb egy base-re meg egy maradekra
igazabol a rest-ben van a base, az object es a task...hasznalatkor meg ezeket osszerakni

**Comment by bakog** [comment]
Ezt a gui-hoz terveztem megcsinálni, ahol egy listából lehet majd választani a várost, a nyelvet, meg a mértékegységet.

**Comment by GeorgeFischhof** [comment]
akkor meg plane szet kell szedni  ;-)
