### ISSUE TITLE
foprogram

### ISSUE THREAD

**Issue by GeorgeFischhof** [bakog/pyweather#7]
sokkal szebb lenne, ha csak 2 fuggvenyhivas lenne benne (es mas nevek)

weather_info = get_weather_info()
display_weather_info(weather_info)

-- o --

aztan majd kesobb (ha lesz idom, felteszem a python programozas csoportba is) ha majd lesz clean architecture -unk, akkor 
output_weather_info(weather_info, destination=screen)

**Comment by bakog** [comment]
Tényleg szebb, átalakítottam.
